# Generated by Django 4.2.5 on 2023-10-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_folio_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='video',
            name='folios',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Folio',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
