# Generated by Django 4.2.5 on 2023-10-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
