# Generated by Django 4.2.5 on 2023-10-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_tipo_video_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='nombre',
            new_name='tipo',
        ),
    ]
