# Generated by Django 5.0 on 2023-12-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_tipo_tipo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Folio', 'verbose_name_plural': 'Folios'},
        ),
    ]
