# Generated by Django 4.2.5 on 2023-10-04 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import folios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2', models.CharField(blank=True, max_length=100, null=True)),
                ('alcaldia', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['colonia'],
            },
        ),
        migrations.CreateModel(
            name='Submotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='folios.motivo')),
            ],
            options={
                'verbose_name': 'Motivo CAD',
                'verbose_name_plural': 'Motivos CAD',
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_id', models.CharField(help_text='El formato debe ser C5/yyyymmdd/nnnnn', max_length=20, unique=True, validators=[folios.models.validate_folio_id])),
                ('usuario', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='folios.submotivo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='folios.ubicacion')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
    ]
