# Generated by Django 5.0 on 2023-12-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0002_alter_submotivo_options_alter_folio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folio',
            options={},
        ),
    ]
