# Generated by Django 5.0 on 2023-12-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0003_alter_folio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folio',
            options={'verbose_name': 'Folio', 'verbose_name_plural': 'Folios'},
        ),
    ]
